#!/bin/ash

##############################################
# Shared Variables                           #
##############################################
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
last_half=X
unset totp_confirm

#########################################################
# Create Directories, Mount Filesystems, Create Devices #
#########################################################
mknod /dev/ttyprintk c 5 3
echo "Heads Output Initialized" > /dev/ttyprintk
mkdir /proc /sys /run /tmp /boot /media 2>&- 1>&-
mkdir -p /tmp/secret
mount /dev 2>/dev/ttyprintk
mount /proc 2>/dev/ttyprintk
mount /sys 2>/dev/ttyprintk
mount -t efivarfs efivarfs /sys/firmware/efi/efivars 2>/dev/ttyprintk
mount -t securityfs security /sys/kernel/security 2>/dev/ttyprintk

################################################################
# Show Initial Message, Setup Clock, Pull in functions/config  #
################################################################
cat /etc/motd
cat /etc/motd > /dev/tty0
hwclock -l -s
. /etc/functions
cat /etc/config* > /tmp/config
. /tmp/config
 
###############
# Enable ZFS  #
###############
if [ "$CONFIG_ZFS" = "y" ]; then
        insmod /lib/modules/spl.ko 2>/dev/ttyprintk
        insmod /lib/modules/zlua.ko 2>/dev/ttyprintk
        insmod /lib/modules/zunicode.ko 2>/dev/ttyprintk
        insmod /lib/modules/zavl.ko 2>/dev/ttyprintk
        insmod /lib/modules/znvpair.ko 2>/dev/ttyprintk
        insmod /lib/modules/zcommon.ko 2>/dev/ttyprintk
        insmod /lib/modules/icp.ko 2>/dev/ttyprintk
        insmod /lib/modules/zfs.ko 2>/dev/ttyprintk
	insmod /lib/modules/ehci-hcd.ko 2>/dev/ttyprintk
	insmod /lib/modules/ehci-pci.ko 2>/dev/ttyprintk
	insmod /lib/modules/xhci-hcd.ko 2>/dev/ttyprintk
	insmod /lib/modules/xhci-pci.ko 2>/dev/ttyprintk
fi

##############
# Setup GPG  #
##############
export GPG_TTY=/dev/console
gpg --import /.gnupg/keys/*.key  /.gnupg/keys/*.asc 2>/dev/null || true

################
# Setup FSTAB  #
################ 
if [ ! -z "$CONFIG_BOOT_DEV" ]; then
        echo >> /etc/fstab "$CONFIG_BOOT_DEV /boot auto defaults,ro 0 0"
fi

######################
#Stage1: Verify TOTP #
######################
while true; do
        date=`date "+%Y-%m-%d %H:%M:%S"`
        seconds=`date "+%s"`
        half=`expr \( $seconds % 60 \) / 30`
        if [ "$half" != "$last_half" ]; then
                last_half=$half;
                tpm nv_readvalue -in 4d47 -sz 312 -of "/tmp/secret/totp.sealed"
                tpm unsealfile -hk 40000000 -if "/tmp/secret/totp.sealed" -of "/tmp/secret/totp.key"
                shred -n 10 -z -u "/tmp/secret/totp.sealed"
                TOTP=`totp -q < "/tmp/secret/totp.key"`
                shred -n 10 -z -u "/tmp/secret/totp.key"

        fi

        echo -n "$date $TOTP: "
        read -t 1 -n 1 -s -p "Verify TOTP before continuing" totp_confirm && break
        echo -ne '\r'
done

echo

################################################################
# Should Not Reach this point in script, secure TPM if you do  #
################################################################
if [ "$CONFIG_TPM" = "y" ]; then
        tpm extend -ix 4 -ic recovery
fi
exec /bin/ash
